version: '3.8'

services:
  app:
    image: golang:1.21-alpine
    container_name: ginniAI-task
    working_dir: /app
    volumes:
      - .:/app                
    ports:
      - "8080:8080" 
    env_file: ".env"           
    command: go run main.go    
